export default [
    {
        "id": 1,
        "name": "chị Nhơn - Chợ Tuy Phước, huyện Tuy Phước, tỉnh Bình Định",
        "code": "CMBDH000001",
        "docnum": 1,
        "currency": "VND",
        "employee": null,
        "address": "Chợ Tuy Phước, huyện Tuy Phước, T. Bình Định\r\r BÌNH ĐỊNH\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": "CMBDH000001",
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "1",
        "listItem": null,
        "contactName": "99",
        "saleEmployee": "-1",
        "dueDate": "2018-04-23",
        "taxDate": "2018-04-23",
        "docDate": "2018-04-23"
    },
    {
        "id": 2,
        "name": "Chị Nhơn- Chợ Bồ Đề, TT Tuy Phước, Huyện Tuy Phước, Bình Định",
        "code": "CMBDH000004",
        "docnum": 2,
        "currency": "VND",
        "employee": null,
        "address": "Chợ Bồ Đề, TT Tuy Phước, Huyện Tuy Phước, Bình Địn\r\r BÌNH ĐỊNH\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": null,
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "2",
        "listItem": null,
        "contactName": "0",
        "saleEmployee": "-1",
        "dueDate": "2018-05-09",
        "taxDate": "2018-05-09",
        "docDate": "2018-05-09"
    },
    {
        "id": 3,
        "name": "Chị Liễu, Phù Cát - Bình Định",
        "code": "CMBDH000003",
        "docnum": 3,
        "currency": "VND",
        "employee": null,
        "address": "Phù Cát Bình Định\r\r BÌNH ĐỊNH\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": null,
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "3",
        "listItem": null,
        "contactName": "0",
        "saleEmployee": "-1",
        "dueDate": "2018-05-10",
        "taxDate": "2018-05-10",
        "docDate": "2018-05-10"
    },
    {
        "id": 4,
        "name": "Chị Nhơn- Chợ Bồ Đề, TT Tuy Phước, Huyện Tuy Phước, Bình Định",
        "code": "CMBDH000004",
        "docnum": 4,
        "currency": "VND",
        "employee": null,
        "address": "Chợ Bồ Đề, TT Tuy Phước, Huyện Tuy Phước, Bình Địn\r\r BÌNH ĐỊNH\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": null,
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "4",
        "listItem": null,
        "contactName": "0",
        "saleEmployee": "-1",
        "dueDate": "2018-06-27",
        "taxDate": "2018-06-27",
        "docDate": "2018-06-27"
    },
    {
        "id": 5,
        "name": "Shop Hoàng Kim - 139 Trần Hưng Đạo - Phan Thiết - Bình Thuận",
        "code": "CMBTN000001",
        "docnum": 5,
        "currency": "VND",
        "employee": null,
        "address": "139 Trần Hưng Đạo, Phan Thiết, Bình Thuận\r\r BÌNH THUẬN\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": "CMBTN000001",
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "5",
        "listItem": null,
        "contactName": "101",
        "saleEmployee": "-1",
        "dueDate": "2018-06-27",
        "taxDate": "2018-06-27",
        "docDate": "2018-06-27"
    },
    {
        "id": 6,
        "name": "Shop Hoàng Kim - 139 Trần Hưng Đạo - Phan Thiết - Bình Thuận",
        "code": "CMBTN000001",
        "docnum": 6,
        "currency": "VND",
        "employee": null,
        "address": "139 Trần Hưng Đạo, Phan Thiết, Bình Thuận\r\r BÌNH THUẬN\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": "CMBTN000001",
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "6",
        "listItem": null,
        "contactName": "101",
        "saleEmployee": "-1",
        "dueDate": "2018-06-27",
        "taxDate": "2018-06-27",
        "docDate": "2018-06-27"
    },
    {
        "id": 7,
        "name": "Shop Hoàng Kim - 139 Trần Hưng Đạo - Phan Thiết - Bình Thuận",
        "code": "CMBTN000001",
        "docnum": 7,
        "currency": "VND",
        "employee": null,
        "address": "139 Trần Hưng Đạo, Phan Thiết, Bình Thuận\r\r BÌNH THUẬN\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": "CMBTN000001",
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "7",
        "listItem": null,
        "contactName": "101",
        "saleEmployee": "-1",
        "dueDate": "2018-06-27",
        "taxDate": "2018-06-27",
        "docDate": "2018-06-27"
    },
    {
        "id": 8,
        "name": "Phan Thị Nguyệt - 26 Nguyễn Công Trứ, TP.BMT, ĐăkLăk",
        "code": "CMDLK000002",
        "docnum": 8,
        "currency": "VND",
        "employee": null,
        "address": "26 Nguyễn Công Trứ, TP.BMT, ĐăkLăk\r\r ĐĂK LẮK\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": "CMDLK000002",
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "8",
        "listItem": null,
        "contactName": "106",
        "saleEmployee": "-1",
        "dueDate": "2018-06-27",
        "taxDate": "2018-06-27",
        "docDate": "2018-06-27"
    },
    {
        "id": 9,
        "name": "Bùi Dương Thoại - 124 Bùi Thị Trường, Khóm 4, phường 5, TP.Cà Mau",
        "code": "CMBTN000004",
        "docnum": 9,
        "currency": "VND",
        "employee": "822",
        "address": "124 Bùi Thị Trường, Khóm 4, P. 5, TP.Cà Mau\r\r BÌNH THUẬN\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": "CMBTN000004",
        "emfirstname": "Thanh",
        "emplastname": "Bành Thị Trang",
        "transportname": "Đường bộ",
        "ref": "9",
        "listItem": null,
        "contactName": "104",
        "saleEmployee": "-1",
        "dueDate": "2018-06-27",
        "taxDate": "2018-06-27",
        "docDate": "2018-06-27"
    },
    {
        "id": 10,
        "name": "Chị Nam Hải -Thôn Châu Thành, Đăkyă, MangYang, Gia Lai",
        "code": "CMGLI000001",
        "docnum": 10,
        "currency": "VND",
        "employee": "612",
        "address": "Thôn Châu Thành, Đăkyă, MangYang, Gia Lai\r\r GIA LAI\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": "CMGLI000001",
        "emfirstname": "Nhật",
        "emplastname": "Bùi Thị",
        "transportname": "Đường bộ",
        "ref": "10",
        "listItem": null,
        "contactName": "111",
        "saleEmployee": "-1",
        "dueDate": "2018-06-28",
        "taxDate": "2018-06-28",
        "docDate": "2018-06-28"
    }
]