export default [
    {
        "id": 1,
        "firstname": "Khanh",
        "lastname": "Tăng Văn",
        "dept": 21,
        "sex": "M",
        "jobtitle": "Tổng GĐ",
        "email": null,
        "homecity": "Bắc Từ Liêm",
        "startdate": "2012-08-06",
        "updatedate": "2019-01-26",
        "usersign": 26,
        "deptname": "Kenh ban buon HN",
        "bankcode": "Vietinbank",
        "bankacount": "19026080996969",
        "birthdate": "1979-03-07",
        "tel": null
    },
    {
        "id": 3,
        "firstname": "Anh",
        "lastname": "Đào Ngọc",
        "dept": 6,
        "sex": "M",
        "jobtitle": "NV lái xe",
        "email": null,
        "homecity": "Đan Phượng",
        "startdate": "2017-02-13",
        "updatedate": "2018-04-23",
        "usersign": 1,
        "deptname": "Phòng HCNS",
        "bankcode": "BIDV",
        "bankacount": "28910000098586",
        "birthdate": "1990-08-25",
        "tel": null
    },
    {
        "id": 4,
        "firstname": "Anh",
        "lastname": "Đoàn Thị Phương",
        "dept": 6,
        "sex": "F",
        "jobtitle": "CV quản trị đào tạo",
        "email": "phuonganhdt@kgvietnam.com",
        "homecity": "Huyện Thủy Nguyên",
        "startdate": "2017-09-06",
        "updatedate": "2018-04-23",
        "usersign": 1,
        "deptname": "Phòng HCNS",
        "bankcode": "BIDV",
        "bankacount": "22210005205579",
        "birthdate": "1994-11-27",
        "tel": null
    },
    {
        "id": 5,
        "firstname": "Anh",
        "lastname": "Tạ Quang",
        "dept": 1,
        "sex": "M",
        "jobtitle": "CV R&D",
        "email": "anhtq@kgvietnam.com",
        "homecity": "Thanh Xuân",
        "startdate": "2015-09-14",
        "updatedate": "2018-04-23",
        "usersign": 1,
        "deptname": "Phòng RD",
        "bankcode": "BIDV",
        "bankacount": "28910000100162",
        "birthdate": "1984-06-27",
        "tel": "911868827"
    },
    {
        "id": 6,
        "firstname": "Anh",
        "lastname": "Nguyễn Kim",
        "dept": 3,
        "sex": "F",
        "jobtitle": "TP Kế hoạch",
        "email": "anhnk@kgvietnam.com",
        "homecity": "Thanh Xuân",
        "startdate": "2015-08-10",
        "updatedate": "2018-04-23",
        "usersign": 1,
        "deptname": "Phòng kế hoạch",
        "bankcode": "BIDV",
        "bankacount": "28910000099932",
        "birthdate": "1980-02-10",
        "tel": "911868823"
    },
    {
        "id": 7,
        "firstname": "Anh",
        "lastname": "Nguyễn Đức",
        "dept": 4,
        "sex": "M",
        "jobtitle": "Photographer",
        "email": "anhnd@kgvietnam.com",
        "homecity": "TP Hải Dương",
        "startdate": "2017-08-24",
        "updatedate": "2018-04-23",
        "usersign": 1,
        "deptname": "Phòng MKT",
        "bankcode": "BIDV",
        "bankacount": "28910000099084",
        "birthdate": "1987-11-23",
        "tel": null
    },
    {
        "id": 9,
        "firstname": "Anh",
        "lastname": "Trần Lê",
        "dept": 18,
        "sex": "F",
        "jobtitle": "Đại diện thương mại",
        "email": "dongnd01@kgvietnam.com",
        "homecity": "Thành Phố Vinh",
        "startdate": "2017-09-01",
        "updatedate": "2018-04-23",
        "usersign": 1,
        "deptname": "Kênh Kwin mien bac",
        "bankcode": "BIDV",
        "bankacount": "51010001181765",
        "birthdate": "1988-10-21",
        "tel": "888965993"
    },
    {
        "id": 10,
        "firstname": "Anh",
        "lastname": "Nguyễn Đức",
        "dept": 14,
        "sex": "M",
        "jobtitle": "Đại diện thương mại",
        "email": "anhnd02@kgvietnam.com",
        "homecity": "Thủy Nguyên",
        "startdate": "2016-08-01",
        "updatedate": "2018-04-23",
        "usersign": 1,
        "deptname": "FSTHN",
        "bankcode": "Techcombank",
        "bankacount": "19031174947868",
        "birthdate": "1991-10-14",
        "tel": "911823359"
    }
]