export default [
    {
        "id": 1,
        "name": "chị Nhơn - Chợ Tuy Phước, huyện Tuy Phước, tỉnh Bình Định",
        "code": "CMBDH000001",
        "docnum": 1,
        "currency": "VND",
        "employee": null,
        "address": "Chợ Tuy Phước, huyện Tuy Phước, T. Bình Định\r\r BÌNH ĐỊNH\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": "CMBDH000001",
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "1",
        "listItem": null,
        "listQuotation": null,
        "saleEmployee": "-1",
        "docDate": "2018-04-21",
        "dueDate": "2018-04-21",
        "taxDate": "2018-04-21",
        "contactName": "99"
    },
    {
        "id": 2,
        "name": "Đặng Thị Cẩm (CH Cẩm) - 133 Nguyễn Thị Minh,Tỉnh Bình Định",
        "code": "CMBDH000002",
        "docnum": 2,
        "currency": "VND",
        "employee": null,
        "address": "133 Nguyễn Thị Minh, T. Bình Định\r\r BÌNH ĐỊNH\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": "CMBDH000002",
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "2",
        "listItem": null,
        "listQuotation": null,
        "saleEmployee": "-1",
        "docDate": "2018-04-21",
        "dueDate": "2018-04-21",
        "taxDate": "2018-04-21",
        "contactName": "100"
    },
    {
        "id": 3,
        "name": "Shop Con Yêu - 89 Thống nhất - Lagi - Hàm Tân, Bình Thuận",
        "code": "CMBTN000003",
        "docnum": 3,
        "currency": "VND",
        "employee": null,
        "address": "89 Thống nhất, Lagi, Hàm Tân, Bình Thuận\r\r BÌNH THUẬN\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": "CMBTN000003",
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "3",
        "listItem": null,
        "listQuotation": null,
        "saleEmployee": "-1",
        "docDate": "2018-04-22",
        "dueDate": "2018-04-23",
        "taxDate": "2018-04-22",
        "contactName": "103"
    },
    {
        "id": 4,
        "name": "NPP  Cty TNHH Hoàng Gia - Hà Giang",
        "code": "DNHGG000002",
        "docnum": 4,
        "currency": "VND",
        "employee": null,
        "address": "Số 113, Đường Nguyễn Thái Học, Tổ 22, P. Minh Khai, TP. Hà Giang, T. Hà Giang, .\r\r HÀ GIANG\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": "Trương Cao Cường",
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "4",
        "listItem": null,
        "listQuotation": null,
        "saleEmployee": "-1",
        "docDate": "2018-04-23",
        "dueDate": "2018-04-23",
        "taxDate": "2018-04-23",
        "contactName": "2130"
    },
    {
        "id": 5,
        "name": "Chị Liễu, Phù Cát - Bình Định",
        "code": "CMBDH000003",
        "docnum": 5,
        "currency": "VND",
        "employee": null,
        "address": "Phù Cát Bình Định\r\r BÌNH ĐỊNH\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": null,
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "5",
        "listItem": null,
        "listQuotation": null,
        "saleEmployee": "-1",
        "docDate": "2018-05-10",
        "dueDate": "2018-05-10",
        "taxDate": "2018-05-10",
        "contactName": "0"
    },
    {
        "id": 6,
        "name": "Shop Vy - Thống nhất, Lagi, Hàm Tân, Bình Thuận",
        "code": "CMBTN000002",
        "docnum": 6,
        "currency": "VND",
        "employee": null,
        "address": "Thống nhất, Lagi, Hàm Tân, Bình Thuận\r\r BÌNH THUẬN\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": "CMBTN000002",
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "6",
        "listItem": null,
        "listQuotation": null,
        "saleEmployee": "-1",
        "docDate": "2018-05-18",
        "dueDate": "2018-05-18",
        "taxDate": "2018-05-18",
        "contactName": "102"
    },
    {
        "id": 7,
        "name": "(17.668-500) Anh Trường - Shop Owen, Cao Lỗ, Đông Anh",
        "code": "CNHNI000084",
        "docnum": 7,
        "currency": "VND",
        "employee": null,
        "address": "73 Cao Lỗ, TT Đông Anh\r\r HÀ NỘI\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": "Anh Trường",
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "7",
        "listItem": null,
        "listQuotation": null,
        "saleEmployee": "-1",
        "docDate": "2018-05-18",
        "dueDate": "2018-05-18",
        "taxDate": "2018-05-18",
        "contactName": "605"
    },
    {
        "id": 8,
        "name": "Chị Nhinh - Thế Mừng Sport - Số 24 Cao Lỗ, TT.Đông Anh",
        "code": "CNHNI000085",
        "docnum": 8,
        "currency": "VND",
        "employee": null,
        "address": "Sè 24 Cao Lỗ, TT.Đông Anh\r\r HÀ NỘI\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": "CNHNI000085",
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "8",
        "listItem": null,
        "listQuotation": null,
        "saleEmployee": "-1",
        "docDate": "2018-05-18",
        "dueDate": "2018-05-18",
        "taxDate": "2018-05-18",
        "contactName": "606"
    },
    {
        "id": 9,
        "name": "Chị Nhinh - Thế Mừng Sport - Số 24 Cao Lỗ, TT.Đông Anh",
        "code": "CNHNI000085",
        "docnum": 9,
        "currency": "VND",
        "employee": null,
        "address": "Sè 24 Cao Lỗ, TT.Đông Anh\r\r HÀ NỘI\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": "CNHNI000085",
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "9",
        "listItem": null,
        "listQuotation": null,
        "saleEmployee": "-1",
        "docDate": "2018-05-18",
        "dueDate": "2018-05-18",
        "taxDate": "2018-05-18",
        "contactName": "606"
    },
    {
        "id": 10,
        "name": "(17.668-500)CH Hương Giang - Phố Nỉ, Sóc Sơn, Đông Anh",
        "code": "CNHNI000131",
        "docnum": 10,
        "currency": "VND",
        "employee": null,
        "address": "Phố Nỉ, Sóc Sơn, Đông Anh\r\r HÀ NỘI\rVIETNAM",
        "shipto": "Tru so",
        "trasnport": -1,
        "slpname": "-No Sales Employee-",
        "cntname": "Chị Giang",
        "emfirstname": null,
        "emplastname": null,
        "transportname": "Đường bộ",
        "ref": "10",
        "listItem": null,
        "listQuotation": null,
        "saleEmployee": "-1",
        "docDate": "2018-05-18",
        "dueDate": "2018-05-18",
        "taxDate": "2018-05-18",
        "contactName": "653"
    },
]