export default [
    {
        "id": 1,
        "name": "Bùi Dương Thoại - 124 Bùi Thị Trường, Khóm 4, phường 5, TP.Cà Mau",
        "code": "CMBTN000004",
        "currency": "VND",
        "employee": null,
        "series": 14,
        "docnum": 1,
        "listItem": null,
        "taxDate": "2018-06-27",
        "docDate": "2018-06-27",
        "contactName": "104",
        "saleEmployee": "-1",
        "dueDate": "2018-07-27",
        "contactCode": null
    },
    {
        "id": 2,
        "name": "Nguyễn Thị Hồng Hà - chợ esup - H. Esup - T. Đăklăk",
        "code": "CMDLK000004",
        "currency": "VND",
        "employee": "31",
        "series": 14,
        "docnum": 2,
        "listItem": null,
        "taxDate": "2018-06-27",
        "docDate": "2018-06-27",
        "contactName": "108",
        "saleEmployee": "-1",
        "dueDate": "2018-07-27",
        "contactCode": null
    },
    {
        "id": 3,
        "name": "Chị Nam Hải -Thôn Châu Thành, Đăkyă, MangYang, Gia Lai",
        "code": "CMGLI000001",
        "currency": "VND",
        "employee": "69",
        "series": 14,
        "docnum": 3,
        "listItem": null,
        "taxDate": "2018-06-27",
        "docDate": "2018-06-27",
        "contactName": "111",
        "saleEmployee": "-1",
        "dueDate": "2018-07-27",
        "contactCode": null
    },
    {
        "id": 4,
        "name": "Mai Phương - ngã 3 Nầm, Hương Sơn, Hà Tĩnh.",
        "code": "CMHTH000004",
        "currency": "VND",
        "employee": "612",
        "series": 14,
        "docnum": 4,
        "listItem": null,
        "taxDate": "2018-06-27",
        "docDate": "2018-06-27",
        "contactName": "119",
        "saleEmployee": "-1",
        "dueDate": "2018-07-27",
        "contactCode": null
    },
    {
        "id": 5,
        "name": "Chị Nhơn- Chợ Bồ Đề, TT Tuy Phước, Huyện Tuy Phước, Bình Định",
        "code": "CMBDH000004",
        "currency": "VND",
        "employee": null,
        "series": 14,
        "docnum": 5,
        "listItem": null,
        "taxDate": "2018-07-03",
        "docDate": "2018-07-03",
        "contactName": "0",
        "saleEmployee": "-1",
        "dueDate": "2018-08-03",
        "contactCode": null
    },
    {
        "id": 6,
        "name": "Shop Vy - Thống nhất, Lagi, Hàm Tân, Bình Thuận",
        "code": "CMBTN000002",
        "currency": "VND",
        "employee": null,
        "series": 14,
        "docnum": 6,
        "listItem": null,
        "taxDate": "2018-07-03",
        "docDate": "2018-07-03",
        "contactName": "102",
        "saleEmployee": "-1",
        "dueDate": "2018-08-03",
        "contactCode": null
    }
]
    